### ISSUE TITLE
Item selection problem with Touch (Mobile)  - Fix

### ISSUE THREAD

**Issue by semercioguz** [loopj/jquery-tokeninput#753]
Change populate_dropdown function's mouseover,mousedown part like this : 

   function populate_dropdown (query, results) {
        ...
                .appendTo(dropdown)
                .on({
                    mouseover:function (event) {
                        select_dropdown_item($(event.target).closest("li"));
                    },
                    mousedown:function (event) {
                        add_token($(event.target).closest("li").data("tokeninput"));
                        hidden_input.change();
                        return false;
                    },
                    touchstart:function (event) {
                        add_token($(event.target).closest("li").data("tokeninput"));
                        hidden_input.change();
                        return false;
                    }
                })
                .hide();

Hope it helps someone..

**Comment by landonconover** [comment]
It helped me. Thanks a bunch.

**Comment by kressly** [comment]
@semercioguz  , @landonconover  Please where are we supposed to make that change ? I have opened the javascript of the tokeninput but i did not see something like that in it ?
Please is that change supposed to be made ?

**Comment by semercioguz** [comment]
@kressly , it seems name of the functions is different with the version I have.  Try to find "populateDropdown" function. Under the "appendTo(dropdown)" part...

**Comment by kressly** [comment]
This plugin would have been far better if people were to answer questions and help each other.

**Comment by hugohenrique** [comment]
This does not make the best or worst plugin.

Read the source code and see what you can find error is occurring case. Make a PR.
And if you have questions about using.

Use something like StackOverflow :+1:

**Comment by kressly** [comment]
I have solved this on my fork

**Comment by Leooo** [comment]
Thank you @semercioguz!
