### ISSUE TITLE
request: minlength [SOLVED]

### ISSUE THREAD

**Issue by bodaonline** [loopj/jquery-tokeninput#757]
Hi,
would be nice to be able to set minimum length of tokens to be added by user. I can restrict this on a DB level but would be nice to see jquery tokeninput show a message: "tag too short"

**Comment by korun** [comment]
Hello! The [`minChars`](http://loopj.com/jquery-tokeninput/#search-settings) option is not what you need?

**Comment by bodaonline** [comment]
yep, found it meanwhile, thx!
