### ISSUE TITLE
[feature request] Callback like onNoResults or beforeFreeTaggingAdd

### ISSUE THREAD

**Issue by CanRau** [loopj/jquery-tokeninput#782]
Would be nice to have a callback like onNoResults or beforeFreeTaggingAdd so that I could place a lable like "press enter to create new tag" :)

This is my first feature request/issue on github, hope it's alright?

**Comment by valerio-bozzolan** [comment]
It isn't necessary:
```
$("#my-text-input").tokenInput("/url/to/your/script/", {
    onResult: function(results) {
        if(results.length === 0) {
            doWhatYouWant();
        }
        return results;
    }
});

```

**Comment by CanRau** [comment]
Thanks! Works like a charm :)
